apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: test-pv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate