apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: project
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 38791
        name: http
        protocol: HTTP
      hosts:
        - "127.0.0.1"