apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project
spec:
  hosts:
    - project
  http:
    - match:
        - headers:
            version:
              exact: v1
      route:
        - destination:
            host: project
            subset: v1
    - match:
        - headers:
            version:
              exact: v2
      route:
        - destination:
            host: project
            subset: v2