apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project
spec:
  hosts:
    - project
  http:
    - route:
        - destination:
            host: project
            subset: v2
          weight: 70
        - destination:
            host: project
            subset: v1
          weight: 30