- name: Check Application Health
  uri:
    url: http://localhost:3000/health
    return_content: yes
  # Register the output of the module in a variable
  register: Devops_health

- name: Print app health
  debug:
    msg: "{{ Devops_health.content }}"


- name: Check Application redis readiness
  uri:
    url: http://localhost:3000/readiness
    return_content: yes
  # Register the output of the module in a variable
  register: Devops_readiness

- name: Print redis running
  debug:
    msg: "{{ Devops_readiness.content }}"