version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisvolume:/data"
  web:
    depends_on:
      - redis
    image: rayanebouaita/devops_project_bouaita_prevost
    ports:
      - "6500:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
volumes:
  redisvolume: