- name: Installation of npm and node
  shell: |
    sudo apt install npm -y
    sudo npm install -g n
    sudo n latest
    sudo timedatectl set-local-rtc 1
    
- name: Installation of redis
  shell: |
    sudo apt-get update -y
    sudo apt install redis-server -y

- name: Starting npm
  shell: |
    cd /home/vagrant/app/userapi/
    npm install --no-bin-links
    npm start &
