Vagrant.configure("2") do |config|

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  config.vm.synced_folder "../", "/home/vagrant/app"
  # Define the gitlab_server VM
  config.vm.define "Devops-Bouaita-Prevost" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "ubuntu/focal64"
    # Specify the VM ip address
    config.vm.network "forwarded_port", guest: 80, host: 8000
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "Devops-Bouaita-Prevost.server.local"
      # VM RAM in MB
      vb.memory = 2048
      # VM CPUs
      vb.cpus = 1
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end
  end
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"

    ansible.tags = "install,healthchecks"

  end
end